version: "3.7"

services:
  database_ilumeo:
    image: postgres
    container_name: database_ilumeo
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=ilumeodb
      - POSTGRES_PASSWORD=ilumeo
      - POSTGRES_DB=database_ilumeo
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: ilumeo_api
    ports:
      - 8080:8080
    volumes:
      - .:/usr/app
    links:
      - database_ilumeo
    depends_on: 
      - database_ilumeo
volumes:
  pgdata:
    driver: local